services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: task-management-client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path:  package.json